### ISSUE TITLE
Meta not saving/fetching

### ISSUE THREAD

**Issue by Dunuin** [mcpierce/comixed#586]
**Describe the bug**
ComiXed hangs most of the tries after pressing "save" or trying to fetch meta data while using the "comicvine" tab.

**To Reproduce**
1. Go to 'Library' -> 'Comics' ->
2. Click on 'any comic'
3. Right click ->"Open comic..."
4. Switch to "ComicVine" tab
5. Edit Series/Volume/Issue# fields
6. Click "Save" or "Fetch" 
7. There is the loading bar at the top but nothing happens

**Expected behavior**
Comixed saves the made changes and/or shows the list of comic series to select the right one returned from ComicVine.

**Desktop (please complete the following information):**
 - ComiXed version: 0.4.9-SNAPSHOT-20191028024557
 - OS: FreeNAS(FreeBSD) server / Win10 client
 - Chrome v77.0.3865.120

**Additional context**
The process uses up to 5GB RAM, I that that shouldn't be normal.
Logfile: [https://pastebin.com/tVA5BNvE](https://pastebin.com/tVA5BNvE)

**Comment by mcpierce** [comment]
@Dunuin I hit this same problem while working on #515. The underlying issue was a mismatched name for the story arc column in the new migration. So this will be fixed when I push this other feature today. Unfortunately it's going to require deleting your database (something only ever an issue on pre-release changes).

When that feature is pushed, can you download the new build generated from it and verify that this problem is fixed? And if it is, please feel free to close this ticket.

**Comment by bareheiny** [comment]
Unrelated to this bug, but related to the fix...and having to delete the CX DB - is there any way to partially migrate data across?

Currently it takes 60 hours to fully load my library (all page hashes created etc.) - I don't mind doing it, but if there are shortcuts I'm very keen on knowing what they are...

**Comment by mcpierce** [comment]
@bareheiny I tried (honestly) to avoid having to delete and re-import things. But, unfortunately, there have been a few things I've discovered now that I'm testing locally with MySQL as well as H2 that have popped up. I did just do a quick google for H2 backup tools, something along the lines of MySQL Workbench, that can dump the contents of the tables so you can recreate your database and then reload the data itself.

I would definitely recommend not loading your library into development releases. They can be relatively stable, but unfortunately we're going to hit situations like this prior to a release that'll break things. 😞

**Comment by bareheiny** [comment]
@mcpierce it's all good, I really don't mind doing a full load as it lets me identify potential problems that I may miss if I only imported a subset of my library.

Although I can likely write some SQL to populate a new DB from an old DB...if I wasn't being lazy of course.

**Comment by mcpierce** [comment]
@bareheiny I've been rethinking the backup/restore feature with this reworking of the frontend code. I'll get something together for the next release so we can save and restore data.

**Comment by Dunuin** [comment]
It is saving now but only "credits", "title" and "cover date" are fetched and nothing from the story tab. After selecting the series and clicking "select" the frontend shows the error "Failed to scrape comic.".
Or is that just not implemented yet? I was trying to fetch this comic which provides story meta: [https://comicvine.gamespot.com/the-x-men-129-god-spare-the-child/4000-20114/](https://comicvine.gamespot.com/the-x-men-129-god-spare-the-child/4000-20114/)

Log: [https://pastebin.com/L55RprZp](https://pastebin.com/L55RprZp)

**Comment by mcpierce** [comment]
@Dunuin I'm testing with my library by telling CX that a comic is that specific issue, and I'm seeing this:

```
{timestamp: "2019-11-04T14:19:49.437+0000", status: 500, error: "Internal Server Error",…}
error: "Internal Server Error"
message: "Failed to get publisher details"
path: "/api/scraping/comics/1079/issue/20114"
status: 500
timestamp: "2019-11-04T14:19:49.437+0000"
```
Looking in the *comic_vine_issues* table I see the comic was loaded and cached. But when I look in the *comic_vine_publishers* table I'm seeing this:

```
<?xml version="1.0" encoding="utf-8"?><!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"><html>  <head>    <title>503 first byte timeout</title>  </head>  <body>    <h1>Error 503 first byte timeout</h1>    <p>first byte timeout</p>    <h3>Guru Mediation:</h3>    <p>Details: cache-fty21322-FTY 1572876932 1094470780</p>    <hr>    <p>Varnish cache server</p>  </body></html>
```

So the scraping code's not recognizing that the data returned when scraping the publisher details was bad and cached it, which caused the rest of the scraping to fail. And since the publisher details are in the database, it's not reloading it.

I'm right now manually trying to query their REST APIs to get info on the publisher (31) and it's timing out for me and not returning JSON.  But querying another publisher (4) it's returning a response. It's very weird, as publisher 31 is Marvel, so maybe they have something bad going on at CV? I can hit [Marvel's page](https://comicvine.gamespot.com/dell/4010-31/) without incident, but going to the JSON API endpoint is timing out for them. So I think this issue is with CV and not CX.

Now, that being said, I did open a bug yesterday (#587) to throw an exception for cases like this so that the bad data doesn't get cached. For now I recommend waiting for 

Regarding the memory issue, is there possibly a comic in  your library of 500 you used that has a particularly huge image in it? Or is there a particularly large comic in that same set? I fixed a bug a few weeks back where CX was loading the entire physical comic file into memory in order to take a hash on it, but that *should* be fixed now. If not, we'll have to do some additional investigation into why that's the case.

**Comment by Dunuin** [comment]
The biggest CBR is 124MB. Not sure whats the biggest picture inside the CBRs/CBZs.
I was watching the process by using the "top" command while importing the 500 comics and the memory demand increased a little bit with each imported comic.

**Comment by bareheiny** [comment]
The memory issue for creating file hashes has been resolved as far as I'm aware.  I was watching the memory usage, and it never climbed above the 2GB upper limit I'd set.  Prior to the bug fix, I was getting spikes of upto 3GB - the largest comic I have is around 1.6GB, but the memory was freed up as soon as the hash had been created.

On Windows 10, the usage chart was peaks and valleys - a spike every time a comic was being processed, followed by a drop and another spike.

**Comment by mcpierce** [comment]
@Dunuin Were you able to reset the caching tables and reproduce the bug? I'm checked in a commit (#587) that should prevent a bad response from ComicVine from being inserted into the database and keep that scenario from causing scraping to fail.

**Comment by Dunuin** [comment]
I deleted both DBs and imported 500 comics again. Still the same problem with RAM climbing up from 1 to 5GB und scraping fails too. But saving changes to "volume", "series" etc works now.

**Comment by mcpierce** [comment]
I"m not sure why you're seeing a memory spike like that, since nothing that I can think of in CX is loading and holding on to huge amounts of data since the fix for comic file hashing was committed.

**Comment by mcpierce** [comment]
That said, I'm going to close this ticket since the metadata scraping is working correctly. If the memory issue persists, we can open a different ticket to track it.

**Comment by Dunuin** [comment]
Is scraping working in general right now? Fetching a single issue from the comicvine tab isn't working and returns "Failed to scrape comic." and if I select multiple comics and click "scrape comics..." the scraping page is now just "UNDER CONSTRUCTION".

**Comment by mcpierce** [comment]
@Dunuin Single comic scraping is working now. If it's failing to scrape a comic there might be issues going on with ComicVine's website. Can you give me the series, volume and issue # you're trying to scrape and I can verify what's going on locally?

The multi-comic scraping needs to be redone for the 0.5.0 release after I reworked the frontend code. I have that in the backlog to be done by EOY for that release.

**Comment by Dunuin** [comment]
Some examples:

Fetching worked but no "story tab entries" fetched: 
- [http://comicvine.gamespot.com/issue/4000-113826](http://comicvine.gamespot.com/issue/4000-113826)
- [https://comicvine.gamespot.com/the-terminator-the-burning-earth-1/4000-32568/](https://comicvine.gamespot.com/the-terminator-the-burning-earth-1/4000-32568/)

Fetching failed:
- All X-Men Comics I tried like [https://comicvine.gamespot.com/the-x-men-139-something-wicked-this-way-comes/4000-20812/](https://comicvine.gamespot.com/the-x-men-139-something-wicked-this-way-comes/4000-20812/)
- [https://comicvine.gamespot.com/the-punisher-war-journal-23-firepower-among-the-ru/4000-33329/](https://comicvine.gamespot.com/the-punisher-war-journal-23-firepower-among-the-ru/4000-33329/)

**Comment by mcpierce** [comment]
There seems to still be an issue with ComicVine and retrieving the publisher details. I'm going to reopen this and see about debugging it in more detail.

For reference, here are the URLs for details on the specific issue from The X-Men:

https://comicvine.gamespot.com/api/volume/4050-2133/?api_key=APIKEY&format=json
https://comicvine.gamespot.com/api/publisher/4010-31/?api_key=APIKEY&format=json
https://comicvine.gamespot.com/api/issue/4000-20114/?api_key=APIKEY&format=json

**Comment by mcpierce** [comment]
I've opened a question on the ComicVine API forums about this:
https://comicvine.gamespot.com/forums/api-developers-2334/error-getting-publisher-error-503-first-byte-timeo-2056272/
